---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-12.04
    provisioner:
      environments_path: 'environments'
      client_rb:
        environment: 'chef11'
    run_list:
      - 'recipe[apt::default]'
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - 'recipe[cobblerd::default]'
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
    excludes:
      - centos-5.11
