---
driver:
  name: vagrant
  network:
    # The source / destination port need to be the same to properly test redirects and such.
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 2048
    cpus: 1

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV.has_key?('CHEF_VERSION') ? ENV['CHEF_VERSION'] : true %>
  # log_level: info

platforms:
  - name: ubuntu-12.04
    provisioner:
      environments_path: 'environments'
      client_rb:
        environment: 'chef11'
    run_list:
      - 'recipe[apt::default]'
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
  - name: centos-7.3
  - name: oracle-7.3
    driver_config:
      box: bento/oracle-7.3

suites:
  - name: default
    run_list:
      - 'recipe[cobblerd::default]'
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
    excludes:
      - centos-5.11
  - name: create-distro
    run_list:
      - 'recipe[cobblerd::default]'
      - 'recipe[cobblerd_test::create_objects]'
      - 'recipe[cobblerd_test::delete_objects]'
    attributes:
      cobblerd:
        iso_test_hostname: <%= ENV.has_key?('COBBLER_ISO_SOURCE') ? ENV['COBBLER_ISO_SOURCE'] : '' %>
