AllCops:
  Exclude:
    - 'Vagrantfile'
    - vendor/**/*
    - testing/vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.4

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Max: 180

StringLiterals:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'metadata.rb'

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 35
