---
# TODO: Fix code so that this file can be removed.

AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'spec/**/*'
  DisplayCopNames: true

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ModuleLength:
  Max: 500

Metrics/MethodLength:
  Max: 75

Metrics/PerceivedComplexity:
  Max: 15

StringLiterals:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Exclude:
    - 'metadata.rb'
