AllCops:
  Exclude:
    - 'Vagrantfile'
  DisplayCopNames: true

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 120

StringLiterals:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Exclude:
    - 'metadata.rb'

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 35
